/**
 * Created by sabir on 02.01.17.
 */
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH_SUCCESS'
export const INITIALIZE_AUTH_FAIL = 'INITIALIZE_AUTH_FAIL'


//articles

export const LOAD_ARTICLES = 'LOAD_ARTICLES'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL'

export const LOAD_ARTICLE = 'LOAD_ARTICLE'
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS'
export const LOAD_ARTICLE_FAIL = 'LOAD_ARTICLE_FAIL'

export const CREATE_ARTICLE = 'CREATE_ARTICLE'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL'

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL'

//memo_speak
export const CREATE_MEMOSPEAK_MATERIAL = 'CREATE_MEMOSPEAK_MATERIAL'
export const CREATE_MEMOSPEAK_MATERIAL_SUCCESS = 'CREATE_MEMOSPEAK_MATERIAL_SUCCESS'
export const CREATE_MEMOSPEAK_MATERIAL_FAIL = 'CREATE_MEMOSPEAK_MATERIAL_FAIL'

export const UPDATE_MEMOSPEAK_MATERIAL = 'UPDATE_MEMOSPEAK_MATERIAL'
export const UPDATE_MEMOSPEAK_MATERIAL_SUCCESS = 'UPDATE_MEMOSPEAK_MATERIAL_SUCCESS'
export const UPDATE_MEMOSPEAK_MATERIAL_FAIL = 'UPDATE_MEMOSPEAK_MATERIAL_FAIL'

export const DELETE_MEMOSPEAK_MATERIAL = 'DELETE_MEMOSPEAK_MATERIAL'
export const DELETE_MEMOSPEAK_MATERIAL_SUCCESS = 'DELETE_MEMOSPEAK_MATERIAL_SUCCESS'
export const DELETE_MEMOSPEAK_MATERIAL_FAIL = 'DELETE_MEMOSPEAK_MATERIAL_FAIL'

export const LOAD_MEMOSPEAK_MATERIALS = 'LOAD_MEMOSPEAK_MATERIALS'
export const LOAD_MEMOSPEAK_MATERIALS_SUCCESS = 'LOAD_MEMOSPEAK_MATERIALS_SUCCESS'
export const LOAD_MEMOSPEAK_MATERIALS_FAIL = 'LOAD_MEMOSPEAK_MATERIALS_FAIL'

export const LOAD_MEMOSPEAK_USER_ANSWERS = 'LOAD_MEMOSPEAK_USER_ANSWERS'
export const LOAD_MEMOSPEAK_USER_ANSWERS_SUCCESS = 'LOAD_MEMOSPEAK_USER_ANSWERS_SUCCESS'
export const LOAD_MEMOSPEAK_USER_ANSWERS_FAIL = 'LOAD_MEMOSPEAK_USER_ANSWERS_FAIL'

export const SAVE_MEMOSPEAK_ANSWERS = 'SAVE_MEMOSPEAK_ANSWERS'
export const SAVE_MEMOSPEAK_ANSWERS_SUCCESS = 'SAVE_MEMOSPEAK_ANSWERS_SUCCESS'
export const SAVE_MEMOSPEAK_ANSWERS_FAIL = 'SAVE_MEMOSPEAK_ANSWERS_FAIL'

//video cache
export const PUT_VIDEOS_IN_CACHING_SET = 'PUT_VIDEOS_IN_CACHING_SET'

export const INITIALIZE_VIDEO_DB = 'INITIALIZE_VIDEO_DB'
export const INITIALIZE_VIDEO_DB_SUCCESS = 'INITIALIZE_VIDEO_DB_SUCCESS'
export const INITIALIZE_VIDEO_DB_FAIL = 'INITIALIZE_VIDEO_DB_FAIL'


export const CACHE_VIDEO = 'CACHE_VIDEO'
export const CACHE_VIDEO_SUCCESS = 'CACHE_VIDEO_SUCCESS'
export const CACHE_VIDEO_FAIL = 'CACHE_VIDEO_FAIL'

//playing
export const PLAYER_PLAY = 'PLAYER_PLAY'
export const PLAYER_PAUSE = 'PLAYER_PAUSE'
export const CHANGE_PLAYER_MODE = 'CHANGE_PLAYER_MODE'


//slides
export const CHANGE_SLIDES = 'CHANGE_SLIDES'
export const CHANGE_CURRENT_SLIDE_NUMBER = 'CHANGE_CURRENT_SLIDE_NUMBER'


//steps
export const CHANGE_USER_MATERIAL_ATTITUDE = 'CHANGE_USER_MATERIAL_ATTITUDE'
export const CHANGE_USER_MATERIAL_ATTITUDE_SUCCESS = 'CHANGE_USER_MATERIAL_ATTITUDE_SUCCESS'
export const CHANGE_USER_MATERIAL_ATTITUDE_FAIL = 'CHANGE_USER_MATERIAL_ATTITUDE_FAIL'

export const LOAD_ATTITUDE_MAP = 'LOAD_ATTITUDE_MAP'
export const LOAD_ATTITUDE_MAP_SUCCESS = 'LOAD_ATTITUDE_MAP_SUCCESS'
export const LOAD_ATTITUDE_MAP_FAIL = 'LOAD_ATTITUDE_MAP_FAIL'

//photos
export const LOAD_PHOTOS = 'LOAD_PHOTOS'
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS'
export const LOAD_PHOTOS_FAIL = 'LOAD_PHOTOS_FAIL'

export const CREATE_PHOTO = 'CREATE_PHOTO'
export const CREATE_PHOTO_SUCCESS = 'CREATE_PHOTO_SUCCESS'
export const CREATE_PHOTO_FAIL = 'CREATE_PHOTO_FAIL'

export const DELETE_PHOTO = 'DELETE_PHOTO'
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS'
export const DELETE_PHOTO_FAIL = 'DELETE_PHOTO_FAIL'

export const UPDATE_PHOTO = 'UPDATE_PHOTO'
export const UPDATE_PHOTO_SUCCESS = 'UPDATE_PHOTO_SUCCESS'
export const UPDATE_PHOTO_FAIL = 'UPDATE_PHOTO_FAIL'
