/**
 * Created by sabir on 13.02.17.
 */

//users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH_SUCCESS'
export const INITIALIZE_AUTH_FAIL = 'INITIALIZE_AUTH_FAIL'


//navigation
export const SWITCH_TAB = 'SWITCH_TAB'

//photos
export const LOAD_PHOTOS = 'LOAD_PHOTOS'
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS'
export const LOAD_PHOTOS_FAIL = 'LOAD_PHOTOS_FAIL'

export const CREATE_PHOTO = 'CREATE_PHOTO'
export const CREATE_PHOTO_SUCCESS = 'CREATE_PHOTO_SUCCESS'
export const CREATE_PHOTO_FAIL = 'CREATE_PHOTO_FAIL'

export const DELETE_PHOTO = 'DELETE_PHOTO'
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS'
export const DELETE_PHOTO_FAIL = 'DELETE_PHOTO_FAIL'

//messages
export const LOAD_MESSAGES = 'LOAD_MESSAGES'
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS'
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL'

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL'




//upload
export const PUT_PHOTOS_IN_UPLOADING_SET = 'PUT_PHOTOS_IN_UPLOADING_SET'
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO'
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS'
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL'

